FROM microsoft/dotnet:2.1-sdk-alpine AS build
WORKDIR /src
ENV HTTPS_PROXY=http://web-proxy.houston.hp.com:8080
COPY ./PluginTester/*.csproj ./PluginTester/
COPY ./PluginCore/*.csproj ./PluginCore/
RUN dotnet restore ./PluginTester/
COPY . ./
RUN dotnet publish ./PluginTester/ -c Debug -o /app

FROM microsoft/dotnet:2.1-runtime-alpine
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "PluginTester.dll"]